feat(docs): updated the document query and webhook sections with clarifications
metriport/metriport pull request #1021
Opened 2023-10-19 23:37 UTC by RamilGaripov

refs. metriport/metriport#1017

### Description

- Added clarifications on the results of the `POST /document/query` calls to relevant sections.

### Screenshots
<img width="697" alt="Screenshot 2023-10-19 at 4 32 00 PM" src="https://github.com/metriport/metriport/assets/90670087/ae0c1624-46d3-4984-8681-1ca3f5d3d473">
<img width="806" alt="Screenshot 2023-10-19 at 4 32 37 PM" src="https://github.com/metriport/metriport/assets/90670087/4be85faa-c585-4d0a-b9cd-0212b507bb7e">

### Release Plan

- Nothing special

2023-10-20 20:53 UTC, leite08 approved these changes

2023-10-24 02:11 UTC, Goncharo requested changes
let's simplify this change - it seems to add too much cognitive overhead for what it's worth

2023-10-24 02:11 UTC, Goncharo commented on docs/_snippets/document-query-complete-tip.mdx
> +  [this endpoint](/medical-api/api-reference/document/get-document).
this is verbose, and at this point the dev might now have a technical understanding of the webhooks - why not just add a quick line to the existing tip? ie

```
<Tip>
  To get updates about the document query progress, including download and conversion status, check
  out our [webhooks guide](/medical-api/more-info/webhooks).
  
  Note that the webhooks will only contain updates for new data fetched in the current document query.
</Tip>
```

2023-10-24 02:11 UTC, Goncharo commented on docs/medical-api/api-reference/document/start-document-query.mdx
> +Note that the webhook resulting from this query **does not** return all of the available documents for a patient - only what was retrieved with this current query.
can remove this if previous comment is addressed

2023-10-24 02:11 UTC, Goncharo commented on docs/medical-api/more-info/webhooks.mdx
I'd remove the other tip and just add a tip here saying something simple like:

<Tip>
  Note that the webhooks will only contain updates for new data fetched in the current document query.
</Tip>

2023-10-28 08:27 UTC, merged