feat(api): get user's connected providers
metriport/metriport pull request #109
Opened 2023-02-13 21:10 UTC by Orta21

Ref. metriport/metriport-internal#346

Ticket: 346

### Dependencies

None

### Description

End point for connected providers

### Release Plan

Merge once approved

2023-02-13 21:24 UTC, Goncharo requested changes

2023-02-13 21:24 UTC, Goncharo commented on packages/packages/api/src/client/metriport.ts
> +    const resp = await this.api.get<string[]>(`/user/${userId}/connect`);
needs updating:
- `@returns Object containing array of connected providers.`
- `Promise<{connectedProviders: string[]}>` 
- `/user/${userId}/connected-providers`

2023-02-13 21:24 UTC, Goncharo commented on docs/user/get-connected-providers.mdx
> +const metriportUserId = await metriportClient.getConnectedProviders("metriportUserId");
`const connectedProviders = ...`

2023-02-13 22:41 UTC, leite08 approved these changes
Just what Dima pointed out, other than that looks good! :shipit:

2023-02-14 00:06 UTC, Goncharo approved these changes
🚢 🚢 🚢

2023-02-14 00:56 UTC, merged