1261 mirth local
metriport/metriport pull request #1204
Opened 2023-11-18 16:25 UTC by Orta21

Ref: #_[ticket-number]_

### Dependencies

- Upstream: _[this PR points to another PR or depends on its release]_
- Downstream: _[PRs that depend on this one, either point to this or can only be released after this one is released]_

### Description

_[Document your changes, give context for reviewers, add images/videos of UI changes]_

### Release Plan

_[Document your release plan to minimize downtime]_

- [ ] Upstream dependencies are met
- [ ] _[action 1]_
- [ ] _[action 2]_

2023-11-21 22:34 UTC, leite08 commented on packages/ihe-server/README.md
I think we're missing some steps here, no? Doesn't one has to perform some operations after starting the docker container?

2023-11-23 05:18 UTC, Goncharo requested changes

2023-11-23 05:18 UTC, Goncharo commented on packages/ihe-server/docker-compose.yml
> +    image: nextgenhealthcare/connect
needs to be `nextgenhealthcare/connect:4.2.2` to match with the plugins

2023-11-23 05:18 UTC, Goncharo commented on packages/ihe-server/docker-compose.yml
> +      - "5435:5432"
let's use `"5436:5432"`, we already have 5435 taken up by another service

2023-11-23 18:15 UTC, Goncharo approved these changes
:shipit:

2023-11-23 19:00 UTC, merged