feat(api): limit patient create sandbox
metriport/metriport pull request #471
Opened 2023-06-08 18:27 UTC by Orta21

Ref. metriport/metriport-internal#764

Ref: 764

### Description

Limit patient create in sandbox mode

### Release Plan

- [ ] Merge once approved

2023-06-08 19:00 UTC, leite08 commented on api/app/src/routes/medical/patient.ts
> +        });
We should probably process this on the Dash and display a user friendly message there, right? Assuming the UI will be available on `sandbox`, of course.

2023-06-09 05:49 UTC, Goncharo requested changes
minor logic issue, also consider @leite08's comment

2023-06-09 05:49 UTC, Goncharo commented on api/app/src/routes/medical/patient.ts
> +      if (numPatients >= Config.SANDBOX_PATIENT_LIMIT) {
should this be `numPatients > Config.SANDBOX_PATIENT_LIMIT`?

otherwise it will error on 20

2023-06-09 21:12 UTC, Goncharo approved these changes
:shipit:

2023-06-09 21:13 UTC, merged