fix(api): add hour to metata schema
metriport/metriport pull request #544
Opened 2023-06-14 19:33 UTC by Orta21

Ref. metriport/metriport-internal#790

Ref: 790

### Dependencies

- Upstream: _[this PR points to another PR or depends on its release]_
- Downstream: _[PRs that depend on this one, either point to this or can only be released after this one is released]_

### Description

Add hour to metadata schema for hourly webhook payloads

### Release Plan

Update packages

- [ ] Upstream dependencies are met
- [ ] Once approved

2023-06-14 20:11 UTC, Goncharo requested changes

2023-06-14 20:11 UTC, Goncharo commented on api/app/src/mappings/apple/index.ts
> +    ...(hourly ? { hour: dayjs(date).format("HH:mm:ss") } : undefined),
If this signifies the hour, should we just have this to always be `HH:00`?

mm:ss might be confusing, especially if they're diff between payloads

2023-06-14 20:11 UTC, Goncharo commented on docs/devices-api/more-info/models.mdx
> +  hour?: string;
We'll need to update all of our docs to include this as an optional field with a description of expected format - right?

2023-06-14 20:20 UTC, Goncharo requested changes

2023-06-14 20:20 UTC, Goncharo commented on docs/devices-api/more-info/apple-health.mdx
> +</Info>
Let's update this to show an example metadata payload & be explicit about what format the `hour` will be in.

2023-06-14 22:47 UTC, Goncharo approved these changes
:shipit:

2023-06-17 16:04 UTC, Orta21 commented
Created a new PR and cherry picked commits

2023-06-17 16:04 UTC, closed without merging