Add NPM workspaces
metriport/metriport pull request #61
Opened 2023-01-22 19:45 UTC by leite08

Ref #143

### Dependencies

- Upstream: https://github.com/metriport/metriport/pull/60
- Downstream: TBD

### Description

Add NPM workspaces.

With this PR, we can do things like:
- `$metriport-internal> npm install` to run `npm install` on all packages automatically
  - likewise for other commands, like `lint` as added on `package.json`
  - including commands that are optional on the packages (with `--if-present`)
- to run a command on a package from the root folder, one can issue `npm run <cmd> -w <package-name>`

### Release Plan

- anytime

2023-01-22 20:55 UTC, leite08 commented
See https://github.com/metriport/metriport-internal/pull/270

2023-01-23 03:45 UTC, Goncharo requested changes

2023-01-23 03:45 UTC, Goncharo commented on package.json
> +    "build:staging": "npm run build -w api && npm run build:staging -w dash && npm run build -w infra",
dash? this is OSS

2023-01-23 04:44 UTC, leite08 commented on package.json
> +    "build:staging": "npm run build -w api && npm run build:staging -w dash && npm run build -w infra",
good catch, missed updating this one

2023-01-23 16:17 UTC, Goncharo approved these changes
🚢

2023-01-23 16:46 UTC, merged