Add commitlint and commitizen
metriport/metriport pull request #63
Opened 2023-01-22 20:51 UTC by leite08

Ref: #92

### Dependencies

- Upstream: https://github.com/metriport/metriport/pull/62
- Downstream: TBD

### Description

- Add [commitlint](https://github.com/conventional-changelog/commitlint)
- Add [commitizen](https://github.com/commitizen/cz-cli)
- Update README

### Release Plan

- anytime

2023-01-22 20:56 UTC, leite08 commented
See https://github.com/metriport/metriport-internal/pull/277

2023-01-23 03:47 UTC, Goncharo requested changes

2023-01-23 03:47 UTC, Goncharo commented on README.md
> +- dash
is this supposed to be widget?

2023-01-23 04:46 UTC, leite08 commented on README.md
> +- dash
yep, good catch

2023-01-23 16:18 UTC, Goncharo approved these changes
🚢

2023-01-23 16:49 UTC, merged