feat(dapi): added revoke token for tenovi
metriport/metriport pull request #834
Opened 2023-08-26 18:04 UTC by RamilGaripov

refs. metriport/metriport#812

### Description

- Users can now revoke their token for Tenovi

### Release Plan

- Nothing special

2023-08-26 19:12 UTC, leite08 requested changes

2023-08-26 19:12 UTC, leite08 commented on packages/api/src/routes/user.ts
> +    const noAuthProvider = new (noAuthProviders[prov] as typeof Apple | typeof Tenovi)();
I suggest we keep the same approach we have for the conditionals on line 181 and 183. Just need to add Tenovi to the no-auth schema on `constants.ts`:

```ts
export const providerNoAuthSchema = z.enum([PROVIDER_APPLE, PROVIDER_TENOVI]);
```

...and update the code here to look like the other scenarios on the "thread" of conditionals.

The key here is to have strong types, minimizing the usage of `as` which removes compiler verification.

2023-08-28 16:02 UTC, leite08 commented on packages/api/src/providers/tenovi.ts
> +        );
Let's avoid adding dynamic information to the error description - if this makes its way to Sentry, it won't be able to group them together.

We could use `MetriportError` and store details on the third parameter to its constructor.

2023-08-28 16:18 UTC, leite08 commented on packages/api/src/routes/user.ts
> +      .json({ message: `Device ${req.query.deviceId} has been removed for user ${userId}.` });
We're defining the `deviceId` query param in two places (inside `removeDevice` and here. I suggest we keep the params being defined/retrieved on the route itself.

2023-08-28 16:18 UTC, leite08 commented on packages/api/src/routes/user.ts
> +  if (!provider || !deviceId) throw new BadRequestError();
Let's add a description to the Error, something like "either provider or deviceId must be provided"

2023-08-28 16:40 UTC, leite08 commented on packages/api/src/routes/user.ts
> +};
Since the other related schemas are on `contants.ts`, maybe we should move this there as well?

2023-08-28 17:18 UTC, RamilGaripov commented on packages/api/src/providers/tenovi.ts
> +      capture.message(`Device ID not found for this user.`, {
Yea, this was definitely intended to be `info` level.

2023-08-28 18:39 UTC, leite08 approved these changes
LGTM, just left a few comments/suggestions that would be nice to do (and learn if you haven't used yet), but NABD.

2023-08-28 18:39 UTC, leite08 commented on packages/api/src/providers/tenovi.ts
> +        });
`additionalInfo` is the 3rd param (good example why `any` is so dangerous)

2023-08-28 18:39 UTC, leite08 commented on packages/api/src/providers/tenovi.ts
>            if (index !== undefined && index !== -1) {
NABD, but `index` cannot be `undefined` anymore

2023-08-28 19:29 UTC, merged